### ISSUE TITLE
loading session file to react implementation of IGV

### ISSUE THREAD

**Issue by Parul-Kudtarkar** [eweitz/igv.js-react#1]
How do I load session file such as this - https://github.com/igvteam/igv.js/blob/b85d1aec4e8ef3ba76a351ea62412d2b42b60056/examples/sessions/igvSession.json

**Comment by eweitz** [comment]
Hi @Parul-Kudtarkar, please ask the IGV team over at https://github.com/igvteam/igv.js/issues.
