### ISSUE TITLE
 The react app cannot load @@Download

### ISSUE THREAD

**Issue by Parul-Kudtarkar** [eweitz/igv.js-react#2]
@eweitz The react app cannot load @@Download, which is proxy to forward @@Download requests to file location in s3
"url": "https://www.encodeproject.org/files/ENCFF576BXP/@@download/ENCFF576BXP.bigWig"
![Screen Shot 2019-08-19 at 2 19 23 PM](https://user-images.githubusercontent.com/22722805/63309717-ac285a80-c2ac-11e9-9821-aa423d59dfea.png)

here is the snapshot of web developer tool

url such as this loads without any issue https://1000genomes.s3.amazonaws.com/phase3/data/HG02450/alignment/HG02450.mapped.ILLUMINA.bwa.ACB.low_coverage.20120522.bam

**Comment by Parul-Kudtarkar** [comment]
import React from 'react';
import igv from 'tmp_es6_igv';
class AppIgv extends React.Component {
componentDidMount() {
var igvContainer = document.getElementById('igv-div');
var igvOptions = {genome:'hg19',locus: 'chr8:128,747,314-128,754,680',tracks: [{url: 'www.diabetesepigenome.org/files/DFF224GGI/@@download/DFF224GGI.bigWig',color:'rgb(150,150,150)',name: 'dga',sourceType: 'file',format: 'bigwig',type: 'wig', height: 50}]};
return igv.createBrowser(igvContainer, igvOptions);
}
render() {
return (

);
}
}
export default AppIgv;

My code

**Comment by eweitz** [comment]
Hi @Parul-Kudtarkar, this repo is merely a minimal example of igv.js in React.  I'm not sure what's causing your issue.  

If you can reduce your issue with igv.js outside React, the IGV team might be able to help you at https://github.com/igvteam/igv.js/issues.
